services:
  # Next.js application
  application:
    container_name: foody-application
    build:
      context: .
      dockerfile: .docker/foody-application/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./code:/home/node/code
      - /home/node/code/foody-application/node_modules
    working_dir: /home/node/code/foody-application
    depends_on: 
      - backend
      - redis
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    tty: true

  # MongoDB Database
  backend:
    container_name: foody-backend
    image: mongo:7.0
    restart: always
    environment:
      DB_NAME: foody
      MONGO_INITDB_DATABASE: foody
    ports:
      - 27017:27017
    volumes:
      - "./.docker/foody-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js"
      - mongodb_data_container:/data/db
  
  # Redis Cache Service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data

volumes:
  mongodb_data_container:
  redis_data_container:
