services:
  # Primary Web Service
  - type: web
    name: foody-application
    runtime: docker
    dockerfilePath: .docker/foody-application/Dockerfile
    dockerBuildTarget: production
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
      - key: AUTH_TRUST_HOST
        value: "true"
      - key: NEXTAUTH_URL
        value: https://foody-1-dlsh.onrender.com/
